[package]
name = "criner"
version = "0.1.0"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2018"
description = "a platform for resumable mining of crates.io for knowledge and information"
publish = false
include = ["src/**/*", "Cargo.*", "README.md", "LICENSE.md"]
license = "MIT"
repository = "https://github.com/crates-io/criner"
readme = "README.md"

[features]
default = []
migration = ["jwalk", "rayon"]

[lib]
doctest = false

[dependencies]
quick-error = "1.2.3"
futures = { version = "0.3.4", features = ["thread-pool"]}
futures-timer = "3.0.1"
# Sled should always be pinned to avoid updates with cargo update. 'sled' is the last know working version
sled = { version = "0.31.0", package = "sled", rev = "9b6b18ecc541f217f0d45d2ad3d910e754ffa08f", git = "https://github.com/spacejam/sled" }
#old_sled = { version = "0.31.0", package = "sled", rev = "af097b1ef4737a0c5ee56a1f72d2a27a88b70db5", git = "https://github.com/spacejam/sled"}
crates-index-diff = "5.0.4"
prodash = { version = "1.1.5", default-features = false, features = ["tui-renderer", "log-renderer"] }
rmp-serde = "0.14.0"
serde_derive = "1.0.104"
serde = "1.0.104"
humantime = "2.0.0"
log = "0.4.8"
async-std = { version = "1.5.0", features = ["unstable"] }
reqwest = { version = "0.10.1", features = ["gzip"] }
http = { version = "0.2.0", default-features = false }
tokio = { version = "0.2", default-features = false, features = ["fs", "rt-threaded"]}
jwalk = { version = "0.4.0", optional = true }
tar = "0.4.26"
libflate = "0.1.27"
itertools = "0.8.2"
bytesize = "1.0.0"
rayon = { version = "1.3.0", optional = true }
rmpv = "0.4.4"
rusqlite = { version = "0.21.0", features = ["bundled"] }

# For 'export' functionality only (embed json in SQL text for simplicity)
serde_json = "1.0.48"
parking_lot = "0.10.0"
