[package]
name = "criner"
version = "0.1.0"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2018"
description = "a platform for resumable mining of crates.io for knowledge and information"
publish = false
include = ["src/**/*", "Cargo.*", "README.md", "LICENSE.md"]
license = "MIT"
repository = "https://github.com/crates-io/criner"
readme = "README.md"

[features]
default = []
migration = ["jwalk"]

[lib]
doctest = false

[dependencies]
quick-error = "1.2.3"
futures = { version = "0.3.4", features = ["thread-pool"]}
futures-timer = "3.0.1"
crates-index-diff = "6.2.0"
prodash = { version = "2.0.0", default-features = false, features = ["tui-renderer", "log-renderer"] }
rmp-serde = "0.14.0"
serde_derive = "1.0.104"
serde = "1.0.104"
humantime = "2.0.0"
log = "0.4.8"
async-std = { version = "1.5.0", features = ["unstable"] }
reqwest = { version = "0.10.1", features = ["gzip"] }
http = { version = "0.2.0", default-features = false }
tokio = { version = "0.2", default-features = false, features = ["fs", "rt-threaded"]}
jwalk = { version = "0.4.0", optional = true }
tar = "0.4.26"
libflate = "0.1.27"
bytesize = "1.0.0"
rmpv = "0.4.4"
rusqlite = { version = "0.21.0", features = ["bundled", "unlock_notify"] }

# For 'export' functionality only (embed json in SQL text for simplicity)
serde_json = "1.0.48"
parking_lot = "0.10.0"
async-trait = "0.1.24"
