[package]
name = "criner-waste-report"
version = "0.1.2"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2018"
description = "Determine include directives for Cargo.toml files to slim down a crate"
include = ["src/**/*", "!**/*_test/*", "Cargo.*", "README.md", "LICENSE.md"]
license = "MIT"
repository = "https://github.com/the-lean-crate/criner"
readme = "README.md"

[lib]
doctest = false

[dependencies]
rmp-serde = "0.14.0"
serde_derive = "1.0.104"
serde = "1.0.104"
tar = "0.4.26"
humantime = "2.0.0"
dia-semver = "8.0.1"

bytesize = "1.0.0"
toml = "0.5.6"
globset = "0.4.4"
horrorshow = "0.8.1"
regex = "1.3.4"
lazy_static = "1.4.0"

